"""create consents

Revision ID: 18c38df1eed9
Revises: 2d237df53933
Create Date: 2026-10-03 08:15:46.146833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18c38df1eed9'
down_revision: Union[str, Sequence[str], None] = '2d237df53933'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consents',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('subject_name', sa.String(length=120), nullable=False),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('permitted_uses', sa.JSON(), nullable=False),
    sa.Column('document_key', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='active', nullable=False),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('withdrawn_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consents_scope'), 'consents', ['scope'], unique=False)
    op.create_index(op.f('ix_consents_status'), 'consents', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_consents_status'), table_name='consents')
    op.drop_index(op.f('ix_consents_scope'), table_name='consents')
    op.drop_table('consents')
    # ### end Alembic commands ###
