"""create voices

Revision ID: 2d237df53933
Revises: 9179952b5a34
Create Date: 2026-10-02 23:56:52.114721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d237df53933'
down_revision: Union[str, Sequence[str], None] = '9179952b5a34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voices',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('language', sa.String(length=4), nullable=False),
    sa.Column('consent_id', sa.String(length=32), nullable=False),
    sa.Column('reference_clip_key', sa.String(length=255), nullable=False),
    sa.Column('embedding_key', sa.String(length=255), nullable=True),
    sa.Column('is_library', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='processing', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voices_consent_id'), 'voices', ['consent_id'], unique=False)
    op.create_index(op.f('ix_voices_language'), 'voices', ['language'], unique=False)
    op.create_index(op.f('ix_voices_status'), 'voices', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_voices_status'), table_name='voices')
    op.drop_index(op.f('ix_voices_language'), table_name='voices')
    op.drop_index(op.f('ix_voices_consent_id'), table_name='voices')
    op.drop_table('voices')
    # ### end Alembic commands ###
