"""roles quotas ownership audit detail

Revision ID: 85d29d421843
Revises: 7ee841b39cb6
Create Date: 2026-10-04 23:16:05.552448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85d29d421843'
down_revision: Union[str, Sequence[str], None] = '7ee841b39cb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('before', sa.JSON(), nullable=True))
    op.add_column('audit_logs', sa.Column('after', sa.JSON(), nullable=True))
    op.add_column('audit_logs', sa.Column('reason', sa.Text(), nullable=True))
    op.add_column('avatars', sa.Column('owner_user_id', sa.String(length=32), nullable=True))
    op.create_index(op.f('ix_avatars_owner_user_id'), 'avatars', ['owner_user_id'], unique=False)
    op.create_foreign_key(None, 'avatars', 'users', ['owner_user_id'], ['id'], ondelete='SET NULL')
    op.add_column('users', sa.Column('role', sa.String(length=16), server_default='user', nullable=False))
    op.add_column('users', sa.Column('rate_limit_per_min', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('max_concurrent_jobs', sa.Integer(), nullable=True))
    op.add_column('voices', sa.Column('owner_user_id', sa.String(length=32), nullable=True))
    op.create_index(op.f('ix_voices_owner_user_id'), 'voices', ['owner_user_id'], unique=False)
    op.create_foreign_key(None, 'voices', 'users', ['owner_user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'voices', type_='foreignkey')
    op.drop_index(op.f('ix_voices_owner_user_id'), table_name='voices')
    op.drop_column('voices', 'owner_user_id')
    op.drop_column('users', 'max_concurrent_jobs')
    op.drop_column('users', 'rate_limit_per_min')
    op.drop_column('users', 'role')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'avatars', type_='foreignkey')
    op.drop_index(op.f('ix_avatars_owner_user_id'), table_name='avatars')
    op.drop_column('avatars', 'owner_user_id')
    op.drop_column('audit_logs', 'reason')
    op.drop_column('audit_logs', 'after')
    op.drop_column('audit_logs', 'before')
    # ### end Alembic commands ###
