"""create avatars

Revision ID: ba6330d3b2b1
Revises: be5a85f5e069
Create Date: 2026-10-03 10:18:58.519224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba6330d3b2b1'
down_revision: Union[str, Sequence[str], None] = 'be5a85f5e069'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('avatars',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('consent_id', sa.String(length=32), nullable=False),
    sa.Column('image_key', sa.String(length=255), nullable=False),
    sa.Column('latents_key', sa.String(length=255), nullable=True),
    sa.Column('is_library', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='processing', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_avatars_consent_id'), 'avatars', ['consent_id'], unique=False)
    op.create_index(op.f('ix_avatars_status'), 'avatars', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_avatars_status'), table_name='avatars')
    op.drop_index(op.f('ix_avatars_consent_id'), table_name='avatars')
    op.drop_table('avatars')
    # ### end Alembic commands ###
