"""drop consent document_key

Revision ID: be5a85f5e069
Revises: 18c38df1eed9
Create Date: 2026-10-03 08:45:57.269143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be5a85f5e069'
down_revision: Union[str, Sequence[str], None] = '18c38df1eed9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('consents', 'document_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consents', sa.Column('document_key', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
